DROP TABLE IF EXISTS TX_PEMBAYARAN_H;

CREATE TABLE TX_PEMBAYARAN_H(
  NO_PEMBAYARAN SERIAL PRIMARY KEY NOT NULL,
  NO_TRANSAKSI VARCHAR(30) NOT NULL FOREIGN KEY REFERENCES Transactions(id),
  TOTAL_TAGIHAN_CICILAN DOUBLE(17,2) NOT NULL,
  TOTAL_TAGIHAN_DENDA DOUBLE(17,2) NOT NULL,
  BIAYA_ADM_TUTUP DOUBLE(17,2) NOT NULL,
  TOTAL_TAGIHAN DOUBLE(17,2) NOT NULL,
  PEMBULATAN int,
  JUMLAH_PEMBAYARAN DOUBLE(17,2) NOT NULL,
  METODE_BAYAR VARCHAR(20) NOT NULL,
  created_date TIMESTAMP NOT NULL,
  creator_id INT4 NOT NULL,
  updated_date TIMESTAMP,
  updater_id INT4,
  deleted_date TIMESTAMP,
  deleter_id INT4,
);

SELECT * FROM TX_PEMBAYARAN_H;